### ISSUE TITLE
Check API key?

### ISSUE THREAD

**Issue by eesazahed** [TheRedstoneRadiant/ippp.gq#3]
Can you check your API KEY in production? Because it's not getting the geolocation API.

![Screen Shot 2022-09-28 at 4 19 45 PM](https://user-images.githubusercontent.com/97064249/192880653-7af21cf8-fb53-4c45-b9fd-a3755e5da7fc.png)

**Comment by TheRedstoneRadiant** [comment]
![image](https://user-images.githubusercontent.com/76220359/192911868-31e60f53-40ec-4da3-916e-9a747c01a315.png)

There's a total of 25,000 searches per month.
I'm just going to wait until October lol

**Comment by eesazahed** [comment]
Alright, thanks anyway. The sites looking good!
